[package]
name = "passive-ddns"
version = "3.1.3"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
env_logger = "0.8"
reqwest = { version = "0.11", features = ["blocking", "json", "cookies"] }
regex = "1"
serde_json = "1"
toml = "0.5"
serde_derive = "1"
serde = { version = "1.0", features = ["derive"] }
