name: Build binary

on:
  push:
    tags-ignore:
      - test**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='passive-ddns_linux_amd64'
            mv target/release/passive-ddns target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='passive-ddns_darwin_amd64'
            mv target/release/passive-ddns target/release/$BIN
          else
            BIN='passive-ddns_windows_amd64.exe'
            mv target/release/passive-ddns.exe target/release/$BIN
          fi
          echo "::set-output name=bin::target/release/$BIN"
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/release/passive-ddns_*
      - name: Check release tag
        id: check_release
        shell: bash
        run: |
          echo "::set-output name=prerelease::$(if [[ $GITHUB_REF =~ beta|alpha ]]; then echo true; else echo false; fi)"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ fromJSON(steps.check_release.outputs.prerelease) }}
          files: ${{ steps.rename.outputs.bin }}