name: Build binary

on:
  push:
    tags-ignore:
      - test**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Update rust
        run: rustup update

      - name: Build binary
        run: |
          cargo build --release

      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='passive-ddns_linux_amd64'
            mv target/release/passive-ddns target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='passive-ddns_darwin_amd64'
            mv target/release/passive-ddns target/release/$BIN
          else
            BIN='passive-ddns_windows_amd64.exe'
            mv target/release/passive-ddns.exe target/release/$BIN
          fi
          echo "::set-output name=bin::target/release/$BIN"
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: artifact
          path: |
            target/release/passive-ddns_*
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.rename.outputs.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rust
        run: rustup target install aarch64-unknown-linux-musl
      - name: Install cross
        run: cargo install cross
      - run: mv target/aarch64-unknown-linux-musl/release/passive-ddns target/aarch64-unknown-linux-musl/release/passive-ddns_linux_aarch64
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: aarch64-artifact
          path: target/aarch64-unknown-linux-musl/release/passive-ddns_linux_aarch64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/aarch64-unknown-linux-musl/release/passive-ddns_linux_aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
